### PR TITLE
Vercel rewrites

### LINKED ISSUE #193: [FEAT] Use vercel rewrites instead of folders for each page
https://vercel.com/docs/edge-network/rewrites
it would make the source code a bit cleaner
example:
```json
{
  "rewrites": [
    {
      "source": "/credits",
      "destination": "/misc/credits.html"
    }
  ]
}
```
or smth like that idk

### PR DESCRIPTION
**Pull request by Bashamega**
closes #193

### CODE REVIEW

**Comment by mariocraft987** [comment]
I see a failing check

**Comment by Bashamega** [comment]
> I see a failing check

Because you need to authorize it

**Comment by mariocraft987** [comment]
hmmm.. either the vercel servers crashed or your thing doesn't work

**Comment by Bashamega** [comment]
> hmmm.. either the vercel servers crashed or your thing doesn't work

It should work

**Comment by mariocraft987** [comment]
yea... something seems sussy wrong

**Comment by dumorando** [comment]
fixed

**Pull request merged**
