### PR TITLE
Donating page

### PR DESCRIPTION
**Pull request by BwnnyRxbbit**
Screenshot 2024-05-13 at 1 05 02 PM

### CODE REVIEW

**Review by Bashamega — CHANGES_REQUESTED** [review]
Hello:)
Please add it inside a what container like what I did with the settings page.

**Comment by qwertyy-dev** [comment]
before merging let's stick allat into a `div.box` for website consistency!

**Review by Bashamega — CHANGES_REQUESTED** [review]
Please move this into a new folder named `donate` and rename it to `index.html`

**Comment by BwnnyRxbbit** [comment]
> Please move this into a new folder named `donate` and rename it to `index.html`

Sure

**Comment by BwnnyRxbbit** [comment]
I'll merge this now.

**Comment by BwnnyRxbbit** [comment]
Can somebody centre it for me and make the box transparent like in the settings page?

**Comment by Bashamega** [comment]
> Can somebody centre it for me and make the box transparent like in the settings page?

I am going to make it

**Comment by BwnnyRxbbit** [comment]
> > Can somebody centre it for me and make the box transparent like in the settings page?
> 
> I am going to make it

Thanks, also do you know why the CSS isn't showing up?

**Comment by Bashamega** [comment]
> > > Can somebody centre it for me and make the box transparent like in the settings page?
> > 
> > 
> > I am going to make it
> 
> Thanks, also do you know why the CSS isn't showing up?

which css?

**Comment by Bashamega** [comment]
I am going to change the meta info and fix the js

**Comment by Bashamega** [comment]
> > > > > Can somebody centre it for me and make the box transparent like in the settings page?
> > > > 
> > > > 
> > > > I am going to make it
> > > 
> > > 
> > > Thanks, also do you know why the CSS isn't showing up?
> > 
> > 
> > which css?
> 
> It seems like some code in `blue dodger.css` aren't appearing.

It is working fine for me

**Comment by BwnnyRxbbit** [comment]
> > > > > > Can somebody centre it for me and make the box transparent like in the settings page?
> > > > > 
> > > > > 
> > > > > I am going to make it
> > > > 
> > > > 
> > > > Thanks, also do you know why the CSS isn't showing up?
> > > 
> > > 
> > > which css?
> > 
> > 
> > It seems like some code in `blue dodger.css` aren't appearing.
> 
> It is working fine for me

Go [here](https://bark-coding.vercel.app/donate/index.html) and press on the "Donate now!" button.

**Comment by Bashamega** [comment]
It is loading the styles @BwnnyRxbbit. If you need a different behavior, you need to modify the CSS.

**Comment by BwnnyRxbbit** [comment]
> It is loading the styles @BwnnyRxbbit. If you need a different behavior, you need to modify the CSS.

If you look in the OP you can see that the "Submit" button is styled and the form is centred.

**Comment by Bashamega** [comment]
> > It is loading the styles @BwnnyRxbbit. If you need a different behavior, you need to modify the CSS.
> 
> If you look in the OP you can see that the "Submit" button is styled and the form is centred.

Well, it is loading. I don't know what the problem is. You may need to revise your CSS, also it can be caused because you only modified the blue dodger them. So, if you are using another theme, then this is the problem. You will need to modify the same changes in the other themes

**Pull request merged**
