### PR TITLE
New Settings Page

### PR DESCRIPTION
**Pull request by Bashamega**
Hello:)
I have customized the settings page and integrated it into the website using js.
image
Solves: #137

### CODE REVIEW

**Comment by qwertyy-dev** [comment]
heck yeah

**Comment by Bashamega** [comment]
Will you merge?

**Comment by qwertyy-dev** [comment]
there's merge conflicts 🥲

**Comment by BwnnyRxbbit** [comment]
It seems like the JavaScript code isn't complete and organised in the sense of closing the {'s.

**Comment by Bashamega** [comment]
> there's merge conflicts 🥲

For some reason i can't resolve them. Github disabled the button

**Comment by Bashamega** [comment]
> It seems like the JavaScript code isn't complete and organised in the sense of closing the {'s.
> 
> Edit: Maybe it might be fine, it might just be because there is a issue merging it.

Yeah in the sense of CSS formatting was bad do i have reformatted it. and added semicolons in my js code.

**Comment by Rubiidev-18** [comment]
I added more review requesters 👍🏻 
also can you make the search bar and text in search bar a lighter ver of the current accent color? the blue looks so bad here. also can you gimme the theme selection snippet of the theme css for future use?

**Comment by Bashamega** [comment]
> I added more review requesters 👍🏻 also can you make the search bar and text in search bar a lighter ver of the current accent color? the blue looks so bad here. also can you gimme the theme selection snippet of the theme css for future use?

This is the code snippet for applying the css:
```
const theme = localStorage.getItem('theme');
if (theme) {
    if (theme.startsWith('#')) {
        const style = document.createElement('style');
        style.innerHTML = `
        .navbar{
            background:${theme};
        }
        `;
        document.head.append(style);
    } else if (theme != "bluedodger") {
        const link = document.createElement('link');
        link.rel = "stylesheet";
        link.href = `https://bark-coding.vercel.app/src/themes/${theme}.css`;
        document.head.append(link);
    };
};
```
Would you prefer the placeholder text will be white?

**Comment by Rubiidev-18** [comment]
yea, it's good.
> Would you prefer the placeholder text will be white?

**Review by BwnnyRxbbit — APPROVED** [review]
This seems good to go once the merge conflicts are fixed.

**Comment by qwertyy-dev** [comment]
i resolved the conflicts, merging now!

**Comment by BwnnyRxbbit** [comment]
> i resolved the conflicts, should i merge

yes

**Comment by BwnnyRxbbit** [comment]
What is the difference between "Bluedodger" and "Classic blue"? and "Browndodger" looks really weird.

**Comment by qwertyy-dev** [comment]
> "Browndodger" looks really weird.

i couldn't agree more 🤣
"classicblue" was the original theme. i gave the ui a revamp and thus, the bluedodger you see today was born

**Comment by BwnnyRxbbit** [comment]
And currently you can't see which theme you have selected.

**Comment by Bashamega** [comment]
> And currently you can't see which theme you have selected.

Would you like me to work on this, i can open a new PR for this

**Comment by BwnnyRxbbit** [comment]
> > And currently you can't see which theme you have selected.
> 
> Would you like me to work on this, i can open a new PR for this

Sure, I'd be happy to help as well.

**Comment by Bashamega** [comment]
> > > And currently you can't see which theme you have selected.
> > 
> > 
> > Would you like me to work on this, i can open a new PR for this
> 
> Sure, I'd be happy to help as well.

I think it would be easy for me to do it, but if i need help i will mention you

**Comment by BwnnyRxbbit** [comment]
> > > > And currently you can't see which theme you have selected.
> > > 
> > > 
> > > Would you like me to work on this, i can open a new PR for this
> > 
> > 
> > Sure, I'd be happy to help as well.
> 
> I think it would be easy for me to do it, but if i need help i will mention you

Ok, I don't think you need to make a PR for this. I think you can just contribute to main.

**Comment by Bashamega** [comment]
> > > > > And currently you can't see which theme you have selected.
> > > > 
> > > > 
> > > > Would you like me to work on this, i can open a new PR for this
> > > 
> > > 
> > > Sure, I'd be happy to help as well.
> > 
> > 
> > I think it would be easy for me to do it, but if i need help i will mention you
> 
> Ok, I don't think you need to make a PR for this. I think you can just contribute to main.

it is sone

**Pull request merged**
