### PR TITLE
[Solve Issue] Scrollable block category bar

### PR DESCRIPTION
**Pull request by Bashamega**
Solves: #132 
image

I fixed the scroll bar, and also refactored all the code using prettier, since it was not formatted.

### CODE REVIEW

**Comment by mariocraft987** [comment]
Wth

**Comment by mariocraft987** [comment]
You have to remove the comment of the whole code of ‘signup.js’

**Comment by Bashamega** [comment]
> You have to remove the comment of the whole code of `signup.js`

I think that i didn't delete anything

**Comment by mariocraft987** [comment]
Well something’s keeping me from merging it

**Comment by Bashamega** [comment]
> Well something’s keeping me from merging it

Why?

**Comment by Bashamega** [comment]
> Idk, some small issues in the code

Can you tell me what are the small issues that are bothering you?
Is it because i have formatted the code?

**Comment by mariocraft987** [comment]
Wth, you changed all 124 files!

**Comment by Bashamega** [comment]
Will you be happy if I didn't format the code?

**Comment by Rubiidev-18** [comment]
there needs to be some resolved conflicts, so, like reformat the conflicting files using the latest versions

**Comment by Rubiidev-18** [comment]
yep, it's all good now! merged!

**Pull request merged**
