### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by Rubiidev-IPad**
3000th commit celebration!

### CODE REVIEW

**Comment by mariocraft987** [comment]
@Rubiidev-IPad , how we gonna make the confetti

**Comment by Rubiidev-IPad** [comment]
> @Rubiidev-IPad , how we gonna make the confetti

copy a js effect from a tutorial as a placeholder ig

**Comment by mariocraft987** [comment]
☠️

**Comment by sillybreakfast** [comment]
> copy a js effect from a tutorial as a placeholder ig

no.

**Pull request merged**
