### PR TITLE
Uploader update

### PR DESCRIPTION
**Pull request by Bashamega**
solves #134

### CODE REVIEW

**Review by qwertyy-dev — APPROVED** [review]
looks good to me, but we need @mariocraft987's approval

**Review by BwnnyRxbbit — APPROVED** [review]

**Comment by BwnnyRxbbit** [comment]
Looks good to me as well! In future maybe be more specific about what you changed/add.

**Comment by Bashamega** [comment]
> Looks good to me as well! In future maybe be more specific about what you changed/add.

Thank you

**Comment by mariocraft987** [comment]
Seems good!

**Comment by BwnnyRxbbit** [comment]
It seems like I'm unable to upload an image now.

**Comment by Bashamega** [comment]
> It seems like I'm unable to upload an image now.

There was an error in the paths, it is working now

**Comment by BwnnyRxbbit** [comment]
> > It seems like I'm unable to upload an image now.
> 
> There was an error in the paths, it is working now

Working now, the edits look amazing!

**Comment by Bashamega** [comment]
> > > It seems like I'm unable to upload an image now.
> > 
> > 
> > There was an error in the paths, it is working now
> 
> Working now, the edits look amazing!

Thanks

**Pull request merged**
