### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by Bashamega**
Hello:)
I have translated it into Arabic, Italian, Mandarin.
NOTE: I used chat gpt from Italian and Mandarin even though i speak them.

### CODE REVIEW

**Review by qwertyy-dev — COMMENTED** [review]
seeing as the only two languages i know are english and asl, i can't clarify the credibility of this... however, as i believe dumorando once said, using chatgpt makes us look unprofessional :(

**Comment by Bashamega** [comment]
> seeing as the only two languages i know are english and asl, i can't clarify the credibility of this... however, as i believe dumorando once said, using chatgpt makes us look unprofessional :(

There is no such word as `dumorando` in the file

**Comment by qwertyy-dev** [comment]
> > seeing as the only two languages i know are english and asl, i can't clarify the credibility of this... however, as i believe dumorando once said, using chatgpt makes us look unprofessional :(
> 
> There is no such word as `dumorando` in the file

the user, @dumorando

**Comment by Bashamega** [comment]
> > > seeing as the only two languages i know are english and asl, i can't clarify the credibility of this... however, as i believe dumorando once said, using chatgpt makes us look unprofessional :(
> > 
> > 
> > There is no such word as `dumorando` in the file
> 
> the user, @dumorando

Sorry. I have misunderstood, i think GPT made a good job. if you want to modify you can

**Comment by qwertyy-dev** [comment]
> > *snip*
> Sorry. I have misunderstood, i think GPT made a good job. if you want to modify you can

i have no idea how to read this language, so i suppose if you think it looks good then we should merge it

**Comment by Bashamega** [comment]
> > > *snip*
> > 
> > Sorry. I have misunderstood, i think GPT made a good job. if you want to modify you can
> 
> i have no idea how to read this language, so i suppose if you think it looks good then we should merge it

It is good.
Merged

**Pull request merged**
