### PR TITLE
Index.js Fefactor

### PR DESCRIPTION
**Pull request by Steve0Greatness**
Refactor `index.js` by rewriting small sections of it.

### CODE REVIEW

**Comment by breakfast-for-dinner** [comment]
have you tested that this works?

**Comment by Steve0Greatness** [comment]
On my local machine, yes

**Comment by mariocraft987** [comment]
You need to change it to `length`, not `lenght` in 084dc8ce07af158fdf52652fabd154babc9a12f7

**Comment by dumorando** [comment]
ill fix it myself

**Pull request merged**
