### PR TITLE
add proper extension system

### PR DESCRIPTION
**Pull request by dumorando**
without this pr all the extensions are automatically added and clicking on them does nothing

this pr makes it so that when you click on the extension image it adds it instead of it already being there

### CODE REVIEW

**Comment by qwertyy-dev** [comment]
great

**Comment by dumorando** [comment]
cna i megre it @mariocraft987

**Comment by nmsderp** [comment]
average dumo w

**Comment by dumorando** [comment]
> average dumo w



> average dumo w

thnak yo u

**Comment by dumorando** [comment]
> average dumo w

nevrmind it did not work average dumo L

image

**Comment by mariocraft987** [comment]
*vine_boom**vine_boom**vine_boom**vine_boom**vine_boom**vine_boom**vine_boom*

**Pull request merged**
