### PR TITLE
Solves A lot of issues

### LINKED ISSUE #143: URL form
Most of the pages ends with .html which is not nice.
I would like to work on removing .html
it would take a lot of my time

### LINKED ISSUE #144: Contributors page
Hello :)
My idea is to create a contributor's page, rather than redirecting the user to the GitHub graphs. I would love to work on this.

### LINKED ISSUE #146: Missing Meta tags
Hello:)
I have noticed that the project lacks meta tags which can make the site more difficult to find online.
I would like to work on that.

### LINKED ISSUE #153: color contrast issues (yes, again 🥲)
when you set the navbar color to a bright color in settings, it doesn't set the text color to black, making it very hard or impossible to read.
Screenshot from 2024-05-11 17-52-33

### PR DESCRIPTION
**Pull request by Bashamega**
closes #153 
closes #144 
closes #143 
closes #146 

Hello:)
This PR closes a lot of issues
image

### CODE REVIEW

**Review by qwertyy-dev — CHANGES_REQUESTED** [review]
awesome!!! only thing is that `jobs/jobs.html` should be changed to `jobs/index.html` and the color contrast issue on the navbar does not get fixed with this pr

**Comment by Bashamega** [comment]
> awesome!!! only thing is that `jobs/jobs.html` should be changed to `jobs/index.html` and the color contrast issue on the navbar does not get fixed with this pr

Sure, I am going to modify the changes

**Review by BwnnyRxbbit — CHANGES_REQUESTED** [review]
Would you be able to add how each of us have contributed? Like by coding or by providing ideas/feedbacks/suggestions a lot ext. Atm, I think everyone is by coding.

**Comment by Bashamega** [comment]
> Would you be able to add how each of us have contributed? Like by coding or by providing ideas/feedbacks/suggestions a lot ext. Atm, I think everyone is by coding.

I will try

**Review by qwertyy-dev — APPROVED** [review]

**Comment by Bashamega** [comment]
Hello @BwnnyRxbbit :)
After intensive research I didn't find a way to add the contributions graph. Also, i tried embedding GitHub in the app but GitHub refused.
If you have a solution please feel free to share it with me

**Comment by BwnnyRxbbit** [comment]
> Hello @BwnnyRxbbit :) After intensive research I didn't find a way to add the contributions graph. Also, i tried embedding GitHub in the app but GitHub refused. If you have a solution please feel free to share it with me

A contribution count would be nice but I was just talking about adding the word "Coder" to each person who is a coder which is everyone here and maybe add a special "Founder" text under Mariokart987. As in the future we might credit those who has been continuously giving us feedback/suggestions ext and translators and ext like in Scratch Addons.

**Comment by Bashamega** [comment]
> > Hello @BwnnyRxbbit :) After intensive research I didn't find a way to add the contributions graph. Also, i tried embedding GitHub in the app but GitHub refused. If you have a solution please feel free to share it with me
> 
> A contribution count would be nice but I was just talking about adding the word "Coder" to each person who is a coder which is everyone here and maybe add a special "Founder" text under Mariokart987. As in the future we might credit those who has been continuously giving us feedback/suggestions ext and translators and ext like in Scratch Addons.

Done

**Review by BwnnyRxbbit — APPROVED** [review]

**Comment by BwnnyRxbbit** [comment]
I'll merge this!

**Comment by BwnnyRxbbit** [comment]
[This](https://bark-coding.vercel.app/contributors) doesn't look right

**Comment by Bashamega** [comment]
> [This](https://bark-coding.vercel.app/contributors) doesn't look right

Sorry, wait one second

**Comment by Bashamega** [comment]
Done @BwnnyRxbbit

**Comment by BwnnyRxbbit** [comment]
> Done @BwnnyRxbbit

This looks absolutely awesome! Does this update real time?

**Comment by qwertyy-dev** [comment]
> Does this update real time?

if you mean it updates without reload, no

**Comment by BwnnyRxbbit** [comment]
> > Does this update real time?
> 
> if you mean it updates without reload, no

Ok, that it updates with load right?

**Comment by qwertyy-dev** [comment]
> > > Does this update real time?
> > 
> > 
> > if you mean it updates without reload, no
> 
> Ok, that it updates with load right?

yup, it's straight from what github tells us

**Comment by Bashamega** [comment]
> > > Does this update real time?
> > 
> > if you mean it updates without reload, no
> 
> Ok, that it updates with load right?

Correct it uses the github API. But note that sometimes it will throw an error because of the request limit. Also, I didn't add any caching of any kind.

**Comment by BwnnyRxbbit** [comment]
> > > > Does this update real time?
> > > 
> > > 
> > > if you mean it updates without reload, no
> > 
> > 
> > Ok, that it updates with load right?
> 
> Correct it uses the github API. But note that sometimes it will throw an error because of the request limit. Also, I didn't add any caching of any kind.

Where can I access the GitHub API from?

**Comment by Bashamega** [comment]
> > > > > Does this update real time?
> > > > 
> > > > 
> > > > if you mean it updates without reload, no
> > > 
> > > 
> > > Ok, that it updates with load right?
> > 
> > Correct it uses the github API. But note that sometimes it will throw an error because of the request limit. Also, I didn't add any caching of any kind.
> 
> Where can I access the GitHub API from?

From: https://api.github.com

**Comment by BwnnyRxbbit** [comment]
> > > > > > Does this update real time?
> > > > > 
> > > > > 
> > > > > if you mean it updates without reload, no
> > > > 
> > > > 
> > > > Ok, that it updates with load right?
> > > 
> > > 
> > > Correct it uses the github API. But note that sometimes it will throw an error because of the request limit. Also, I didn't add any caching of any kind.
> > 
> > 
> > Where can I access the GitHub API from?
> 
> From: https://api.github.com

Ahh fascinating! Thanks

**Pull request merged**
